*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZHR_OT_CODESTOP.                  " Global Data
  INCLUDE LZHR_OT_CODESUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZHR_OT_CODESF00                        . " subprograms
  INCLUDE LZHR_OT_CODESI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZHR_OT_CODESF...                  " Subprograms
* INCLUDE LZHR_OT_CODESO...                  " PBO-Modules
* INCLUDE LZHR_OT_CODESI...                  " PAI-Modules
