*&---------------------------------------------------------------------*
*&  Include           ZHTMI004_WARP_IHR_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN : BEGIN OF BLOCK s0 WITH FRAME TITLE text-s04.
                                                           "#EC SHAREOK

SELECTION-SCREEN : BEGIN OF BLOCK s1 WITH FRAME TITLE text-s03.

SELECTION-SCREEN : BEGIN OF LINE.
PARAMETERS : rb_pres RADIOBUTTON GROUP r1 DEFAULT 'X'
USER-COMMAND upd.

SELECTION-SCREEN COMMENT 4(40) text-p01 FOR FIELD rb_pres.

SELECTION-SCREEN : POSITION 50.

PARAMETERS : rb_appl RADIOBUTTON GROUP r1.
SELECTION-SCREEN COMMENT 54(40) text-p02 FOR FIELD rb_appl.

SELECTION-SCREEN : END OF LINE,SKIP 1.

*SELECTION-SCREEN :BEGIN OF LINE .
*SELECTION-SCREEN COMMENT 1(11) text-p03 FOR FIELD p_file1.
PARAMETERS : p_file1 TYPE rlgrap-filename MODIF ID f1."VISIBLE
*PARAMETER:p_fold  TYPE char100.
*LENGTH
                                                            "100.
PARAMETERS : p_file3 TYPE rlgrap-filename MODIF ID f2.
*PARAMETERS : p_fname1 TYPE rlgrap-filename.
*SELECTION-SCREEN : END OF LINE.

SELECTION-SCREEN : END OF BLOCK s1.


SELECTION-SCREEN : BEGIN OF BLOCK s2 WITH FRAME TITLE text-b04.

SELECTION-SCREEN : BEGIN OF LINE.
PARAMETERS : rb_test RADIOBUTTON GROUP r2 DEFAULT 'X'
USER-COMMAND upd.

SELECTION-SCREEN COMMENT 4(40) text-s01 FOR FIELD rb_test.

SELECTION-SCREEN : POSITION 50.

PARAMETERS : rb_prod RADIOBUTTON GROUP r2.
SELECTION-SCREEN COMMENT 54(40) text-s02 FOR FIELD rb_prod.

SELECTION-SCREEN : END OF LINE.
SELECTION-SCREEN :SKIP 1.
PARAMETERS       : rb_ndis TYPE char01 RADIOBUTTON GROUP r3
DEFAULT 'X' MODIF ID on1.
PARAMETERS       : rb_scr TYPE char01 RADIOBUTTON GROUP r3
MODIF ID on1.
PARAMETERS       : rb_error TYPE char01 RADIOBUTTON GROUP r3
MODIF ID on1.
PARAMETERS :p_sess(11) MODIF ID on1.
SELECTION-SCREEN : END OF BLOCK s2.

*SELECTION-SCREEN : BEGIN OF BLOCK s4 WITH FRAME TITLE text-s06.
**SELECTION-SCREEN : BEGIN OF LINE.
**SELECTION-SCREEN COMMENT 1(11) text-p06 FOR FIELD p_file2 MODIF ID p1.
*PARAMETERS : p_file2 TYPE rlgrap-filename MODIF ID p1.
**PARAMETERS : p_fname2 TYPE rlgrap-filename MODIF ID p1.
**SELECTION-SCREEN : END OF LINE.
*SELECTION-SCREEN : END OF BLOCK s4.
SELECTION-SCREEN : END OF BLOCK s0.
