*&---------------------------------------------------------------------*
*&  Include           ZHTMI008_CATSDBFI_CATSDBHR_SL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.
PARAMETERS:p_upd AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-004.
PARAMETERS:p_begda TYPE begda ."DEFAULT sy-datum.
SELECTION-SCREEN END OF BLOCK b3.

SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-005.
  PARAMETERS:p_begda1 TYPE begda ."DEFAULT sy-datum.
SELECTION-SCREEN END OF BLOCK b4.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-002.
PARAMETERS:p_dest TYPE tbdls-logsys OBLIGATORY ."DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK b2.
